if(CMAKE_HOST_LINUX)
  set(TOOLCHAIN /usr/bin)
  set(GCC_POSTFIX "")
else()
  message(FATAL_ERROR "Host type is not supported")
endif()

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# Compiler hardware specific flags
set(CMAKE_C_FLAGS "")
set(CMAKE_CXX_FLAGS ${CMAKE_C_FLAGS})
add_compile_definitions(x86)

set(CMAKE_C_COMPILER ${TOOLCHAIN}/gcc${GCC_POSTFIX})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN}/g++${GCC_POSTFIX})
set(CMAKE_AR ${TOOLCHAIN}/ar${GCC_POSTFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
